# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            STECH
tagline:          'music for the moving image'
description:      'music for the moving image'
url:              # https://fongandrew.github.io
baseurl:          #'/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Krisztian Hofstadter'
  url:            https://khofstadter.info

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Custom vars
version:            3.7.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:           https://github.com/krisztian-hofstadter-tedor/stech

disqus:
  shortname:      hydeout

google_analytics: UA-100461102-1

future: true
